version: "3.4"

services:
  api:
    container_name: pokedex-api
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Api/Dockerfile
    depends_on:
      - sqlite3
    networks:
      - default

networks:
  default:
    driver: bridge
    name: db_network
